group=cn.dreeam.leaf
mcVersion=26.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2
# Dummy
channel=ALPHA

paperCommit=c9e894d3cc03f21f80de4f4061a795e11941e89a

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
