group=cn.dreeam.leaf
mcVersion=26.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2
# Dummy
channel=ALPHA

paperCommit=19ebc4a49b725b1ea813f95ac559a2ed3931ee4c

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
