group=cn.dreeam.leaf
mcVersion=26.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2
# Dummy
channel=ALPHA

paperCommit=6c8d413223ba7fa2dc1c508f96741f49950a90d0

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
