name: CN | 问题反馈
description: 创建一个问题反馈来帮助我们进步！
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        在反馈问题之前，请确保您正在使用最新版本的 Leaf，并浏览 [Issues](https://github.com/Winds-Studio/Leaf/issues)，检查你的问题是否已被汇报！

  - type: checkboxes
    attributes:
      label: 是否已存在相关问题？
      description: |
        请浏览 [Issues](https://github.com/Winds-Studio/Leaf/issues)，并检查你的问题是否已被别人汇报！
      options:
        - label: 我已经浏览过Issue，并确保汇报的不是已知问题
          required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 清晰简洁地描述所观察到的行为。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 所期望的行为
      description: 清晰简洁地描述您预期发生的情况。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 如何复现？
      description: 简单描述复现此问题的步骤
      placeholder: |
        1. 进入服务器 '...'
        2. 输入/example '...'
        3. 服务器崩溃 '...'
        4. 在控制台看到报错
    validations:
      required: true

  - type: input
    attributes:
      label: Spark profiler 链接
      description: |
        粘贴你的 Spark profiler 链接到此处，Spark profiler 往往包含了对解决此问题有用的信息，
        查阅 https://spark.lucko.me/docs/ 来学习如何使用Spark。
    validations:
      required: true

  - type: input
    attributes:
      label: 错误日志 (如存在)
      description: 请上传完整的报错信息或完整日志到 https://mclo.gs 或 https://gist.github.com ，并将链接粘贴在此处。
