name: Build Pull Request

on:
  pull_request:
    branches: [ "ver/26.2" ]

jobs:
  build:
    # Run workflow only on main repo
    if: ${{ github.repository == 'Winds-Studio/Leaf' }}
    runs-on: blacksmith-8vcpu-ubuntu-2404
    env:
      MC_VERSION: "26.2"

    steps:
      - name: Checkout repository
        uses: useblacksmith/checkout@v1

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew applyAllPatches --stacktrace --no-daemon
      - name: Create PaperclipJar
        run: ./gradlew createPaperclipJar --stacktrace --no-daemon

      - name: Rename Paperclip JARs
        run: |
          mv leaf-server/build/libs/leaf-paperclip-${{ env.MC_VERSION }}*.jar ./leaf-${{ env.MC_VERSION }}.jar

      - name: Upload Leaf
        uses: actions/upload-artifact@v7
        with:
          path: ./leaf-${{ env.MC_VERSION }}.jar
          archive: false
