name: Build Leaf 1.21.4
on:
  push:
    branches: [ "ver/1.21.4" ]
jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      GRAALVM_ARGS: "-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.LoopUnroll=true -Dgraal.SpeculativeGuardMovement=true --add-modules jdk.incubator.vector"
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" applyAllPatches --stacktrace --no-daemon --parallel

      - name: Create MojmapPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" createMojmapPaperclipJar --stacktrace --no-daemon --parallel

      - name: Create ReobfPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" -Dpaperweight.debug=true createReobfPaperclipJar --stacktrace --no-daemon --parallel

      - name: Rename Paperclip JARs
        run: |
          mv leaf-server/build/libs/leaf-paperclip-1.21.4-R0.1-SNAPSHOT-mojmap.jar ./leaf-1.21.4-${{ env.BUILD_NUMBER }}-mojmap.jar
          mv leaf-server/build/libs/leaf-paperclip-1.21.4-R0.1-SNAPSHOT-reobf.jar ./leaf-1.21.4-${{ env.BUILD_NUMBER }}-reobf.jar

      - name: Publish API
        continue-on-error: true
        run: |
          echo "REPO_USER=${{ secrets.REPO_USER }}" >> $GITHUB_ENV
          export REPO_USER=${{ secrets.REPO_USER }}
          echo "REPO_PASSWORD=${{ secrets.REPO_PASSWORD }}" >> $GITHUB_ENV
          export REPO_PASSWORD=${{ secrets.REPO_PASSWORD }}
          ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" publish --parallel
          # Uncomment when ready to implement:
          # ./gradlew -Dorg.gradle.jvmargs="${{ env.GRAALVM_ARGS }}" publishDevBundlePublicationToLeafRepository -PpublishDevBundle=true --parallel

      - name: Upload Leaf as build artifact
        uses: actions/upload-artifact@main
        with:
          name: Leaf 1.21.4
          path: ./leaf-1.21.4-*.jar

      - name: Prepare for release
        continue-on-error: true
        run: |
          mv ./leaf-1.21.4-${{ env.BUILD_NUMBER }}-mojmap.jar ./leaf-1.21.4-${{ env.BUILD_NUMBER }}.jar
          gh release delete ver-1.21.4 --cleanup-tag -y -R Winds-Studio/Leaf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Leaf
        uses: softprops/action-gh-release@master
        with:
          name: "Leaf 1.21.4"
          tag_name: "ver-1.21.4"
          files: "./leaf-1.21.4-${{ env.BUILD_NUMBER }}.jar"
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          prerelease: false
